
<h1>Kardex de Inventario</h1>

<div id="getInventarioList"></div>

<input type="hidden" name="pageNo" id="pageNo" value="1" />
<input type="hidden" name="urlbase" id="urlbase" value="<?php echo $this->url('kardex/inventario', array('controller' => 'Inventario', 'action' => 'get-inventario-list')) ?>" />



<script>

    jQuery(document).ready(function(){

        var url = '/kardex/inventario/get-inventario-list';
        //return false;
        jQuery.ajax({
            url: url,
            type: 'GET',
            dataType: 'html',
            data: {},
            success: function(data, status){
                jQuery('#getInventarioList').html(data);
            }
        });

    });

</script>