<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/jqueryUI/themes/base/jquery-ui.min.css'); ?>
<!-- Js -->
<?php  $this->headScript()
    ->appendFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui.min.js')
    ->appendFile($this->basePath() . '/js/modules/facturacion/proveedor-ajaxform.js'); ?>

<a id="showform" href="<?php echo $this->url('facturacion/default', array('action' => 'showform' , 'controller' => 'proveedor')); ?>">Crear Proveedor</a>

<!-- empty div to save dialog temporary -->
<div id="winpopup"></div>