<?php
$title = 'Listado de Categorias';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-sm-1 col-md-1"></div>
    <div class="col-sm-10 col-md-10">
        <div class="panel panel-primary">

            <div class="panel-heading text-center">
                <h3><?php echo $this->escapeHtml($title); ?></h3>
            </div>

            <div class="panel-body text-center">
                <div class="row">
                    <div class="col-sm-6 col-md-6"><h3>Categorias Disponibles</h3></div>
                    <div class="col-sm-6 col-md-6">
                        <?php echo $this->paginationControl($this->paginator,'sliding','partial/paginator.phtml',array('route' => 'categoria')); ?>
                    </div>

                </div>
                <div class="row well text-center">
                    <?php foreach ($paginator as $categoria ): ?>

                        <div class="col-sm-6 col-md-3">
                            <a href="<?php echo $this->url('categoria', array('action'=>'edit', 'id' => $categoria->getId()));?>" class="thumbnail">
                                <img src="<?= $categoria->getImagen() ?>" alt="<?= $categoria->getNombre() ?>">
                                <div class="caption">
                                    <h4 id="categoria<?= $categoria->getId() ?>"><?= $categoria->getNombre() ?></h4>
                                </div>
                            </a>
                        </div>

                    <?php endforeach ?>
                </div>

            </div>
            <div class="panel-footer text-right">
                <a href="<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'admin')); ?>" class="btn btn-default">Volver</a>
                <a href="<?php echo $this->url('categoria', array('action'=>'add'));?>" class="btn btn-primary">Crear Nueva Marca</a>
            </div>
        </div>
    </div>
    <div class="col-sm-1 col-md-1"></div>

</div>