<?php
$form = $this->editUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/zfcuseradmin/edit', array('userId' => $this->userId)));
$form->setAttribute('method', 'post');
?>


<div class="row">
    <div class="col-sm-3 col-md-3"></div>
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading text-center"><h1>Editar Usuario</h1></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <div style="float:left; padding-right:16px;"><?php echo $this->htProfileImage($this->userId) ?></div>
                        <a href="<?php echo $this->url('zfcuser/htimageupload') ?>"><?php echo $this->translate('Upload image'); ?></a>
                    </div>
                    <div class="col-sm-8 col-md-8">
                        <div class="well">
                            <?php include '_form.phtml'; ?>
                        </div>
                    </div>
                </div>


            </div>

            <div class="panel-footer text-center">

                <div class="row">
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list');?>" class="btn btn-default">Volver</a>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/remove', array('userId' => $this->userId)); ?>"
                       onclick="return confirm('<?php echo $this->translate('Really delete user?') ?>')" class="btn btn-danger">
                        <?php echo $this->translate('Eliminar') ?>
                    </a>

                </div>

            </div>
        </div>
    </div>
    <div class="col-sm-3 col-md-3"></div>
</div>