<?php
$title = 'Notificar Producto Agotado';
$this->headTitle($title);
?>
<div class="row"><h1><?php echo $this->escapeHtml($title); ?></h1></div>

<div class="panel panel-primary">
    <div class="panel-heading text-center">
        <h3>Seleccione Marca</h3>
        <div class="row">

            <form id="my_form" action="<?php $this->url('agotado'); ?>" method="post">
                <ol class="breadcrumb">
                    <input type="hidden" name="Todos" value="0" />
                    <li class="active"><input type="submit" class="btn btn-primary" name="selmarca" value="Todos" /></li>
                    <?php foreach ($marcas as $marca ): ?>
                        <input type="hidden" name="<?php echo $marca->getNombre() ?>" value="<?php echo $marca->getId() ?>" />
                        <li><input type="submit" class="btn btn-info" name="selmarca" value="<?php echo $marca->getNombre() ?>" /></li>
                    <?php endforeach ?>
                </ol>

            </form>

        </div>
    </div>
    <div class="panel-body text-center">
        <div class="row">
            <div class="col-sm-6 col-md-6"><h3>Productos Disponibles</h3></div>
            <div class="col-sm-6 col-md-6">
                <?php echo $this->paginationControl($this->productos,'sliding','partial/paginator.phtml',array('route' => 'agotado')); ?>
            </div>

        </div>
        <div class="row well text-center">
            <?php foreach ($productos as $producto ): ?>

                <div class="col-sm-6 col-md-2">
                    <a href="<?php echo $this->url('agotado', array('action'=>'notificar', 'id' => $producto->getId()));?>" class="thumbnail">

                        <img src="<?= $producto->getImagen() ?>" alt="<?= $producto->getNombre() ?>">
                        <div class="caption">
                            <h4 id="producto<?= $producto->getId() ?>"><?= $producto->getNombre() ?></h4>
                            <h3>Disponible:</h3>
                            <h3><?= $producto->getCantidad() ?> <?= $producto->getNombunidmedventas() ?></h3>
                        </div>
                    </a>
                </div>

            <?php endforeach ?>
        </div>

    </div>
    <div class="panel-footer text-right">
        <a href="<?php echo $this->url('despacho'); ?>" class="btn btn-default">Volver</a>
    </div>
</div>





