<?php
$title = 'Notificar Producto Agotado en Tienda';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Está seguro que desea notificar el producto '<?php echo $this->escapeHtml($producto->getNombre()); ?>' está Agotado?</p>
<p> Esto generará una merma de <?= $producto->getCantidad() ?> <?= $producto->getNombunidmedventas() ?></p>
<?php
$url = $this->url('agotado', array('action' => 'notificar', 'id'=>$id)); ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="submit" name="notificar" value="Si" />
        <input type="submit" name="notificar" value="No" />
    </div>
</form>