<?php
$title = 'Notificar Producto Agotado en Tienda';
$this->headTitle($title);
?>


<div class="jumbotron">
    <div class="container text-center">
        <h2><?php echo $this->escapeHtml($title); ?></h2>

        <p>Está seguro que desea notificar que el producto '<?php echo $this->escapeHtml($producto->getNombre()); ?>' está agotado en tienda?</p>
        <p>Esto generará una merma de <?= $this->escapeHtml(round($producto->getCantidad()*100)/100) ?> <?= $producto->getNombunidmedventas() ?> del producto </p>
        <p>y realizará una solicitud del producto a almacén. </p>
        <?php
        $url = $this->url('agotado', array('action' => 'notificar', 'id'=>$id)); ?>
        <form action="<?php echo $url; ?>" method="post">
            <div>
                <input class="btn btn-danger btn-lg" type="submit" name="notificar" value="Si" />
                <input class="btn btn-primary btn-lg" type="submit" name="notificar" value="No" />
            </div>
        </form>
    </div>
</div>