<?php
$title = 'Solicitar Producto';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-sm-3 col-md-3"></div>
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-warning">
            <div class="panel-heading text-center"><h1><?php echo $this->escapeHtml($title); ?></h1></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail well well-sm">
                            <img src="<?= $producto->getImagen(); ?>" alt="<?= $this->escapeHtml($producto->getNombre()) ?>">
                            <div class="caption text-center">
                                <h3 id="producto<?= $producto->getId() ?>"><?= $this->escapeHtml($producto->getNombre()) ?></h3>
                                <p>Categoría:<?= $this->escapeHtml($producto->getNombcategoria()) ?></p>
                                <p>Precio:<?= $this->escapeHtml($producto->getPreciounidad()) ?> BsF por  <?= $this->escapeHtml($producto->getNombunidmedventas()) ?></p>

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8 col-md-8">
                        <div class="well">
                            <?php if ($agotado):?>
                            <div class="row">
                               <h4 class="text-center"><strong><?= $this->escapeHtml('¡Producto Agotado en Tienda!') ?></strong></h4>
                            </div>
                            <?php else : ?>
                            <div class="row">
                                <h3>El Sistema reporta la existencia de <?= $this->escapeHtml(round($producto->getCantidad()*100)/100) ?> <?= $this->escapeHtml($producto->getNombunidmedventas()) ?> del producto disponibles en tienda ...</h3>
                                <h3>Que desea hacer a continuación</h3>
                            </div>
                                <div class="row">
                                    <div class="col-sm-6 col-md-6"><a href="<?php echo $this->url('agotado');?>" class="btn btn-success">Actualizar<br>Inventario</a></div>
                                    <div class="col-sm-6 col-md-6"><a href="<?php echo $this->url('agotado', array('action'=>'notificar', 'id' => $producto->getId()));?>" class="btn btn-danger">Notificar<br>Producto Agotado</a></div>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
                </div>


            </div>

            <div class="panel-footer text-center">

                <div class="row">
                    <div class="col-sm-6 col-md-6"><a href="<?php echo $this->url('agotado');?>" class="btn btn-default">Cancelar</a></div>
                    <?php $url = $this->url('agotado', array('action' => 'solicitar-producto', 'id'=>$id)); ?>
                    <form action="<?php echo $url; ?>" method="post">
                        <div class="col-sm-6 col-md-6">
                            <div class="col-sm-4 col-md-4">
                                <input class="btn btn-primary" type="submit" name="solicitar" value="Solicitar Producto" />
                            </div>

                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-md-3"></div>
</div>
