<div class="container text-center">

    <div class="row">
        <div class="col-sm-1 col-md-1"></div>
        <div class="col-sm-10 col-md-10">
            <div class="panel panel-primary">

                <div class="panel-heading text-center">
                    <h3>Detalles del Lote</h3>
                </div>

                <div class="panel-body ">

                    <div class="row">
                        <table class="table" >
                            <thead>
                                <tr>
                                    <th class="text-center">Producto</th>
                                    <th class="text-center">Costo</th>
                                    <th class="text-center">Vencimiento</th>
                                    <th class="text-center">Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->detallesLote as $key => $detalle) {  ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($detalle['nombproducto']) ?></td>
                                    <td><?php echo $this->escapeHtml($detalle['costo'] ) ?></td>
                                    <td><?php echo $this->escapeHtml($detalle['vencimiento'] ) ?></td>
                                    <td><a href="<?php echo $this->url('kardex/inventario/wildcard',array('controller' => 'lote', 'action' => 'edit-detalle', 'id' => $detalle['id'])) ?>" class="btn btn-sm btn-default">Editar</a></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                    </div>

                </div>
                <div class="panel-footer text-right">
                    <a href="<?php echo $this->url('kardex/inventario',array('controller' => 'lote', 'action' => 'index')); ?>" class="btn btn-default">Volver</a>

                </div>
            </div>
        </div>
        <div class="col-sm-1 col-md-1"></div>

    </div>


</div>