<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/jqueryUI/themes/base/jquery-ui.min.css'); ?>
<!-- Js -->
<?php  $this->headScript()
    ->appendFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui.min.js')
    ->appendFile($this->basePath() . '/js/modules/kardex/lote-new-detalle.js'); ?>

<?php
$title = 'Editar Detalle del Lote';
$this->headTitle($title);
?>


<div class="row">
    <div class="col-sm-3 col-md-3"></div>
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading text-center"><h3><?php echo $this->escapeHtml($title); ?></h3></div>
            <div class="panel-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('kardex/inventario/wildcard', array('controller' => 'lote','action' => 'edit-detalle', 'id' => $form->get('id')->getValue())));
                $form->get('submit')->setAttribute('value', 'Editar');
                $formLabel = $this->plugin('formLabel');
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>

                <?php echo $this->formHidden($form->get('id'));?>
                <?php echo $this->formHidden($form->get('lote')); ?>
                <?php echo $this->formHidden($form->get('producto')); ?>

                <div class="row">
                    <div class="col-sm-6 col-md-6 well">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('numlote')); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formRow($form->get('nombproducto')); ?>
                        </div>

                    </div>

                    <div class="col-sm-6 col-md-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('costo')); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formRow($form->get('vencimiento')); ?>
                        </div>

                    </div>
                </div>
            </div>
            <div class="panel-footer text-right">
                <a href="<?php echo $this->url('kardex/inventario/wildcard',array('controller' => 'lote', 'action' => 'detalles', 'idlote' => $form->get('lote')->getValue() )) ?>" class="btn btn-default">Volver</a>
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
    <div class="col-sm-3 col-md-3"></div>
</div>

<!-- empty div to save dialog temporary -->
<div id="winpopup"></div>