<?php
$title = 'Editar Unidad de Medida';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-4 col-md-4"></div>
    <div class="col-sm-4 col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
            <div class="panel-body">
                <div class="well">


                    <?php
                    $form = $this->form;
                    $url = $this->url('unidad-medida', array('action' => 'edit', 'id' => $id));
                    $form->setAttribute('action', $url);
                    $form->get('submit')->setAttribute('value', 'Editar');
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    ?>

                    <div class="row text-center">
                        <div class="col-sm-12 col-md-12">
                            <div class="form-group row">
                                <?php echo $this->formRow($form->get('abreviatura')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row text-center">
                        <div class="col-sm-12 col-md-12">
                            <div class="form-group row">
                                <?php echo $this->formRow($form->get('simbolo')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row text-center">
                        <div class="col-sm-12 col-md-12">
                            <?php echo $this->formRow($form->get('nombre')); ?>
                        </div>
                    </div>


                </div>
            </div>

            <div class="panel-footer text-center">
                <a href="<?php echo $this->url('unidad-medida'); ?>" class="btn btn-default">Volver</a>
                <?php echo $this->formInput($form->get('submit')); ?>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
    <div class="col-sm-4 col-md-4"></div>
</div>






