<?php
$title = 'Listado de Unidades de Medidas';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-sm-4 col-md-4"></div>
    <div class="col-sm-4 col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
            <div class="panel-body">
                <!-- List group -->
                <div class="">
                    <?php foreach ($this->unidadesMedida as $unidadMedida): ?>
                        <div class="list-group">
                            <a href="<?php echo $this->url('unidad-medida', array('action'=>'edit', 'id' => $unidadMedida->getId()));?>" class="list-group-item list-group-item-default ">

                            <div class="row">

                                    <div class="col-sm-6 col-md-6">
                                        <p>Abreviatura:<?= $unidadMedida->getAbreviatura() ?></p>
                                        <p>Símbolo:<?= $unidadMedida->getSimbolo() ?></p>

                                    </div>
                                    <div class="col-sm-6 col-md-6">
                                        <h3 id="unidadMedida<?= $unidadMedida->getId() ?>"><?= $unidadMedida->getNombre() ?></h3>
                                    </div>


                                </div>
                            </a>
                        </div>


                    <?php endforeach; ?>
                </div>
            </div>

            <div class="panel-footer text-center">
                <a href="<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'admin')); ?>" class="btn btn-default">Volver</a>
                <a class="btn btn-primary" href="<?php echo $this->url('unidad-medida', array('action'=>'add'));?>" >Nuevo</a>

            </div>
        </div>
    </div>
    <div class="col-sm-4 col-md-4"></div>
</div>






